name: build

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.17'
      - name: Run GoReleaser for branch [Main]
        uses: goreleaser/goreleaser-action@v2.6.1
        with:
          distribution: goreleaser
          version: latest
          args: -f .goreleaser.yml --snapshot --rm-dist